# Environment configuration
settings:
  docker:
    requirements: requirements.txt
    environment:
      WANDB_DISABLED: "true"
    python_package_installer: uv

# Model Control Plane configuration
model:
  name: YeOldeEnglishTranslator
  description: Model to translate from old to modern english
  tags: ["quickstart", "llm", "t5"]

# Configure the pipeline
parameters:

# Per step configuration
steps:
