# Changes here will be overwritten by Copier
_commit: 2024.10.30
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
hyperparameters_tuning: false
metric_compare_promotion: true
notify_on_failures: false
notify_on_successes: false
open_source_license: none
product_name: supply_chain_forecasting
project_name: Supply Chain Forecasting
target_environment: production
version: 0.0.1
zenml_server_url: ''
